# NOTE 
#   this configuration does not create any data node
#   Your need to create data node service via docker cli
#
# REFERENCES:
# - https://docs.docker.com/compose/compose-file/
# - https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
# 
version: '3.4'
services:
  # ElasticSearch Coordinating nodes
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG:-5.6.9}
    environment:
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
      cluster.name: ${CLUSTER_NAME:-elastic_cluster}
      node.name: "Coordinating-{{.Node.Hostname}}"
      node.master: "false"
      node.data: "false"
      node.ingest: "false"
      discovery.zen.minimum_master_nodes: 2
      discovery.zen.ping.unicast.hosts: tasks.elasticsearch-master
      MAX_LOCKED_MEMORY: unlimited
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.watcher.enabled: 'false'
      xpack.ml.enabled: 'false'
      bootstrap.memory_lock: "true"
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    depends_on:
      - elasticsearch-master
    deploy:
      endpoint_mode: dnsrr
      mode: global
      resources:
        limits:
          memory: 2G
        reservations:
          cpus: '0.30'
          memory: 1500M
      placement:
        constraints: [ node.role == manager ]
    configs:
      - source: limits.conf
        target: /etc/security/limits.conf
    networks:
      elastic_net:
    healthcheck:
        test: ping -c1 localhost >/dev/null 2>&1 || exit 1
        interval: 1m
        timeout: 10s
        retries: 3
  # ElasticSearch Master nodes
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG:-5.6.9}
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
      cluster.name: ${CLUSTER_NAME:-elastic_cluster}
      network.host: _eth0:ipv4_
      node.name: "Master-{{.Node.Hostname}}"
      node.master: "true"
      node.data: "false"
      node.ingest: "false"
      discovery.zen.minimum_master_nodes: 2
      discovery.zen.ping.unicast.hosts: tasks.elasticsearch-master
      MAX_LOCKED_MEMORY: unlimited
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.watcher.enabled: 'false'
      xpack.ml.enabled: 'false'
      bootstrap.memory_lock: "true"
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.60'
          memory: 3G
        reservations:
          cpus: '0.30'
          memory: 2G
      placement:
        constraints: [ node.role == manager ]
    configs:
      - source: limits.conf
        target: /etc/security/limits.conf
    networks:
      elastic_net:
  # https://github.com/justwatchcom/elasticsearch_exporter
  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.0.2
    command:
      - '-es.uri=http://elasticsearch:9200'
    ports:
      - 9108:9108
    networks:
      elastic_net:

volumes:
  es_data:

configs:
  limits.conf:
    file: ./limits.conf

networks:
  elastic_net:
    external:
      name: ${ELASTICSEARCH_NETWORK_NAME:-elasticsearch}
    
