# References:
# - https://docs.docker.com/compose/compose-file/compose-file-v2/
# - https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
version: '2'
services:
  # ElasticSearch Master nodes
  elasticsearch:
    image: elasticsearch:5.6.9-alpine
    volumes:
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200
      - 9300
    #scale: 2
  # ElasticSearch data nodes
  elasticsearch-data:
    image: elasticsearch:5.6.9-alpine
    volumes:
      - ./elastic/elasticsearch-data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200
      - 9300
  kibana:
    image: kibana:5.6.9
    ports:
      - 5601:5601
  cerebro:
    image: yannart/cerebro:latest
    ports:
      - 9000:9000
