version: '3.4'
services:
  kibana:
    image: kibana:${TAG:-5.6.9}
    ports:
      - 5601:5601
    networks:
      elastic_net:
    deploy:
      placement:
        constraints: [ node.role == worker ]
networks:
  elastic_net:
    external:
      name: ${ELASTICSEARCH_NETWORK_NAME:-elasticsearch}
    
